version: '3.9'

services:
  db:
    image: mysql:8.0.23
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: wp_db
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_pass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'

  wp:
    depends_on:
      - db
    build:
      context: ../docker
      dockerfile: Dockerfile
    ports:
      - 8080:80
    restart: always
    volumes:
      - wp_data:/var/www/html
      - ./wp-content/plugins:/var/www/html/wp-content/plugins
      - ./wp-content/mu-plugins:/var/www/html/wp-content/mu-plugins
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_pass
      WORDPRESS_DB_NAME: wp_db
volumes:
  wp_data:
  db_data: