version: '3.9'

services:
  db:
    image: mysql:8.0.23
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: $WP_DB_NAME
      MYSQL_USER: $WP_DB_USER
      MYSQL_PASSWORD: $WP_DB_PASS
      MYSQL_RANDOM_ROOT_PASSWORD: '1'

  wp:
    depends_on:
      - db
    build:
      context: ../docker
      dockerfile: Dockerfile
    ports:
      - 8080:80
    restart: always
    volumes:
      - wp_data:/var/www/html
      - ./wp-content/plugins:/var/www/html/wp-content/plugins
      - ./wp-content/mu-plugins:/var/www/html/wp-content/mu-plugins
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: $WP_DB_USER
      WORDPRESS_DB_PASSWORD: $WP_DB_PASS
      WORDPRESS_DB_NAME: $WP_DB_NAME
  # wp-cli:
  #   depends_on:
  #     - db
  #     - wp
  #   image: wordpress:cli
  #   user: www-data
  #   command: >
  #     /bin/sh -c '
  #     sleep 20;
  #     wp core install --path="/var/www/html" --url="http://localhost:8000" --title="Local Wordpress By Docker" --admin_user=admin --admin_password=secret --admin_email=foo@bar.com
  #     '
  #   volumes:
  #     - wp_data:/var/www/html
  #   environment:
  #     WORDPRESS_DB_HOST: db
  #     WORDPRESS_DB_USER: $WP_DB_USER
  #     WORDPRESS_DB_PASSWORD: $WP_DB_PASS
  #     WORDPRESS_DB_NAME: $WP_DB_NAME
volumes:
  wp_data:
  db_data:
